version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: booktures_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rmcf
      - POSTGRES_DB=booktures
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: